server {
    listen 3000;
    server_name localhost;

    # Onde os arquivos do React vão ficar
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # A MÁGICA ACONTECE AQUI:
        # Tenta carregar a URL exata ($uri), depois tenta como diretório ($uri/), 
        # se falhar em tudo, manda para o index.html (onde o React assume o roteamento)
        try_files $uri $uri/ /index.html;
    }

    # (Opcional) Dica de performance: faz o cache de imagens, CSS e JS no navegador
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }
}