"""add receita_favoritas table

Revision ID: 03d03d49a6f0
Revises: 89f219c0ef4a
Create Date: 2026-03-10 22:36:03.236799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d03d49a6f0'
down_revision: Union[str, Sequence[str], None] = '89f219c0ef4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receita_favoritas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'receita_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receita_favoritas')
    # ### end Alembic commands ###
