"""correcao relacionamento user receita

Revision ID: 19b4f19d6bfb
Revises: 84a5f18e1b07
Create Date: 2026-01-20 00:52:40.927095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b4f19d6bfb'
down_revision: Union[str, Sequence[str], None] = '84a5f18e1b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receitas', sa.Column('id_usuario', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'receitas', 'users', ['id_usuario'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receitas', type_='foreignkey')
    op.drop_column('receitas', 'id_usuario')
    # ### end Alembic commands ###
