"""adiciona tabela receitas

Revision ID: 84a5f18e1b07
Revises: 672388626618
Create Date: 2025-12-29 22:12:27.370446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a5f18e1b07'
down_revision: Union[str, Sequence[str], None] = '672388626618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('tempo', sa.Integer(), nullable=False),
    sa.Column('porcoes', sa.Integer(), nullable=False),
    sa.Column('ingredientes', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('imagem_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receitas_id'), 'receitas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receitas_id'), table_name='receitas')
    op.drop_table('receitas')
    # ### end Alembic commands ###
