"""Remodelagem do banco

Revision ID: 89f219c0ef4a
Revises: d0955927d6c8
Create Date: 2026-02-10 17:42:44.361528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f219c0ef4a'
down_revision: Union[str, Sequence[str], None] = 'd0955927d6c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientes_id'), 'ingredientes', ['id'], unique=False)
    op.create_index(op.f('ix_ingredientes_nome'), 'ingredientes', ['nome'], unique=True)
    op.create_table('receita_categorias',
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.PrimaryKeyConstraint('receita_id', 'categoria_id')
    )
    op.create_table('receita_ingredientes',
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.PrimaryKeyConstraint('receita_id', 'ingrediente_id')
    )
    op.add_column('receitas', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.add_column('receitas', sa.Column('tempo_minutos', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('receitas_id_usuario_fkey'), 'receitas', type_='foreignkey')
    op.create_foreign_key(None, 'receitas', 'users', ['usuario_id'], ['id'])
    op.drop_column('receitas', 'ingredientes')
    op.drop_column('receitas', 'tempo')
    op.drop_column('receitas', 'categoria')
    op.drop_column('receitas', 'id_usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receitas', sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('receitas', sa.Column('categoria', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('receitas', sa.Column('tempo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('receitas', sa.Column('ingredientes', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'receitas', type_='foreignkey')
    op.create_foreign_key(op.f('receitas_id_usuario_fkey'), 'receitas', 'users', ['id_usuario'], ['id'])
    op.drop_column('receitas', 'tempo_minutos')
    op.drop_column('receitas', 'usuario_id')
    op.drop_table('receita_ingredientes')
    op.drop_table('receita_categorias')
    op.drop_index(op.f('ix_ingredientes_nome'), table_name='ingredientes')
    op.drop_index(op.f('ix_ingredientes_id'), table_name='ingredientes')
    op.drop_table('ingredientes')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
