"""Path da imagem na tabela receitas agr é opcional

Revision ID: d0955927d6c8
Revises: 19b4f19d6bfb
Create Date: 2026-01-20 23:39:19.966407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0955927d6c8'
down_revision: Union[str, Sequence[str], None] = '19b4f19d6bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receitas', 'imagem_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receitas', 'imagem_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
